[project]
name = "nn"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "ananthvk", email = "-"},
]
dependencies = ["jupyter>=1.1.1", "jupyterlab>=4.5.5", "numpy>=2.4.3", "scikit-learn>=1.8.0", "matplotlib>=3.10.8", "pandas>=3.0.1", "torch>=2.10.0"]
requires-python = ">=3.14"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
typecheck = "mypy log_analyser --strict"
format = { composite = [
    "ruff check . --fix",
    "ruff format .",
    "ruff check . --select I --fix",
    "black .",
] }
test = "pytest"
codespell = "codespell"
check = { composite = [
    "pdm run format",
    "pdm run typecheck",
    "pdm run test",
    "pdm run codespell",
] }


[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "mypy>=1.19.1",
    "black>=26.1.0",
    "ruff>=0.15.4",
    "codespell>=2.4.1",
]

[[tool.pdm.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
verify_ssl = true
include_packages = ["torch", "torch-*", "pytorch"]
exclude_packages = ["*"]
